### ISSUE TITLE
Fix restriction

### ISSUE THREAD

**Issue by aubertc** [peterbro1/IRDC-CCSK#17]
Example:

```
java -jar target/RCCS-2.75-jar-with-dependencies.jar --dL "(a|'a)\{a}"
------| Actionable Labels |------
[0] a0
[1] 'a1
[2] Tau{'a1, a0}
------------
(a0)|('a1)\{a2}
```

If you have ""(a|'a)\{a}"", then you cannot act on a nor 'a, you can only do tau. Restriction on a means "you cannot communicate along channel a", which means "you cannot input or output on a", so both a and 'a should be forbidden: the only possible transition is tau.

**Comment by aubertc** [comment]
This broke one of the test, I am afraid.

Also, I don't think it is fixed, actually:

```
  java -jar target/RCCS-2.75-jar-with-dependencies.jar --dL "(a|'a)\{a}"
------| Actionable Labels |------
[0] 'a1
[1] Tau{'a1, a0}
------------
(a0)|('a1)\{a2}
Please input the index of the label you'd like to act on:
0
(a0)|('a1)\{a2} -'a1-> (a0)|([k1]0)\{a2}
------| Actionable Labels |------
[0] [k1]
------------
(a0)|([k1]0)\{a2}

```

**Comment by peterbro1** [comment]
> This broke one of the test, I am afraid.
> 
> Also, I don't think it is fixed, actually:
> 
> ```
>   java -jar target/RCCS-2.75-jar-with-dependencies.jar --dL "(a|'a)\{a}"
> ------| Actionable Labels |------
> [0] 'a1
> [1] Tau{'a1, a0}
> ------------
> (a0)|('a1)\{a2}
> Please input the index of the label you'd like to act on:
> 0
> (a0)|('a1)\{a2} -'a1-> (a0)|([k1]0)\{a2}
> ------| Actionable Labels |------
> [0] [k1]
> ------------
> (a0)|([k1]0)\{a2}
> ```

Referenced in Todo. This issue will be a bit more challenging than I originally thought.

The way restrictions work, any process *a* that is restricted along *a* will simply not pass the label a as actionable to parent actions. The parent actions are the ones that determine synchronizing capabilities, so if the actionable label *a* is not offered, then it has no way of knowing if it can synchronize

**Comment by aubertc** [comment]
I am not sure I understand your comment. The issue here is not that `a` is passed while it should not, but that `\bar{a}` is passed while it should not.

Also, please try to be more specific: a process `a` _should_ pass the label `a` as actionable no matter what, the question is what happens to `a \ a`, that is completely stuck. However, `(a | \out{a})\a` is such that
- `a` should "know" that `\out{a}` can send `\out{a}`, 
- `\out{a}` should "know" that `a` can send `a`, 
- `a | \out{a}` should tell the outside world that it can do a, \out{a} or \tau,
- _but, finally_, `(a | \out{a})\a` should tell the outside world that it can do only \tau.

I believe you have all the steps correct except for the last one.

**Comment by peterbro1** [comment]
> I am not sure I understand your comment. The issue here is not that `a` is passed while it should not, but that `\bar{a}` is passed while it should not.
> 
> Also, please try to be more specific: a process `a` _should_ pass the label `a` as actionable no matter what, the question is what happens to `a \ a`, that is completely stuck. However, `(a | \out{a})\a` is such that
> 
> * `a` should "know" that `\out{a}` can send `\out{a}`,
> * `\out{a}` should "know" that `a` can send `a`,
> * `a | \out{a}` should tell the outside world that it can do a, \out{a} or \tau,
> * _but, finally_, `(a | \out{a})\a` should tell the outside world that it can do only \tau.
> 
> I believe you have all the steps correct except for the last one.

I believe it should act correctly now, but I will leave the issue open in case I messed it up.

**Comment by aubertc** [comment]
I believe, too, that it is fixed now. Excellent!
